# Generated by Django 3.2.5 on 2021-07-28 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('V', 'VAREJO'), ('A', 'ATACADO')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=50)),
                ('data_nasc', models.DateField()),
                ('whatsapp', models.CharField(max_length=50)),
                ('data_cadastro', models.DateField()),
                ('tipo_cliente', models.ForeignKey(db_column='categoria', on_delete=django.db.models.deletion.CASCADE, related_name='id_tipo_cliente', to='relatorios_okr.tipocliente')),
            ],
        ),
    ]
