# Generated by Django 3.2.5 on 2021-07-28 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios_okr', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientes',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tipocliente',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='clientes',
            table='Clientes',
        ),
        migrations.AlterModelTable(
            name='tipocliente',
            table='TipoCliente',
        ),
    ]
